### ISSUE TITLE
Rerunning resets script fails when using MySQL as DB backend

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#63]
Content of `./config` directory (inside the `ufdl-backend` repo dir):

```
__init__.py
mysql.py
```

Content of `mysql.py` is the same as `settings.py` but with the following `DATABASES` configuration:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/my.cnf',
        },
    }
}
```

MySQL backend requires:
* `mysql_config` is required by the `mysqlclient` Python library (`sudo apt-get install libmysqlclient-dev`)
* `mysqlclient` library (`pip install mysqlclient`)

Content of `/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/my.cnf`:

```ini
[client]
database = ufdl
user = ufdl
password = ufdl
default-character-set = utf8
host = localhost
sql_mode='STRICT_TRANS_TABLES'
```

With the database `ufdl` being empty, the `ufdl.api_site.scripts.reset` script succeeds.

However, when rerunning it, it fails with the following error message (for some reason it wants to delete the SQLite DB?):

```
metal:[115]~/development/projects/waikato-ufdl/ufdl-backend>export PYTHONPATH="."; export DJANGO_SETTINGS_MODULE="config.mysql"; ./venv.dev/bin/python -m ufdl.api_site.scripts.reset
Database '/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/db.sqlite3' not present; skipping deletion...
Filesystem 'fs' not present; skipping deletion...
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/2.2/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, simple_django_teams, ufdl-core, ufdl-image-classification, ufdl-object-detection, ufdl-speech
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Traceback (most recent call last):
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'admin' for key 'username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/api_site/scripts/reset.py", line 46, in <module>
    reset()
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/api_site/scripts/reset.py", line 38, in reset
    User.objects.create_superuser("admin", "admin@admin.net", "admin")
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/contrib/auth/models.py", line 162, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/contrib/auth/models.py", line 145, in _create_user
    user.save(using=self._db)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'admin' for key 'username'")
```

**Comment by csterling** [comment]
The `reset.py` script doesn't do any clever dropping-of-tables to reset the database, if simply deletes the SQLite file from disk, and if it doesn't exist, no-ops.

So if you're using another database (i.e. MySQL), the resetting of the database still "succeeds" (no-ops because the SQLite file is absent from disk) but then fails during migration as it tries to create a duplicate `admin` user in the (unchanged) MySQL database.

I'll look at making this actually reset the database (whatever type you are using) so this doesn't happen in future.

**Comment by csterling** [comment]
@fracpete I have pushed a potential fix for this in 76848ce6483bbf64a6601493aa825cd0bdc028d2, can you please test if this works for the MySQL database?

**Comment by fracpete** [comment]
Unfortunately, didn't fix everything. Calling the reset the second time now generates now this:

```
Resetting DB...
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/2.2/ref/databases/#mysql-sql-mode
Operations to perform:
  Unapply all migrations: ufdl-core
Running migrations:
  Rendering model states... DONE
  Unapplying ufdl-speech.0005_job_templates... OK
  Unapplying ufdl-speech.0004_pretrained_models... OK
  Unapplying ufdl-speech.0003_docker... OK
  Unapplying ufdl-speech.0002_add_data_domain... OK
  Unapplying ufdl-speech.0001_initial... OK
  Unapplying ufdl-object-detection.0005_job_templates... OK
  Unapplying ufdl-object-detection.0004_pretrained_models... OK
  Unapplying ufdl-object-detection.0003_docker... OK
  Unapplying ufdl-object-detection.0002_add_data_domain... OK
  Unapplying ufdl-object-detection.0001_initial... OK
  Unapplying ufdl-image-classification.0005_job_templates... OK
  Unapplying ufdl-image-classification.0004_pretrained_models... OK
  Unapplying ufdl-image-classification.0003_docker... OK
  Unapplying ufdl-image-classification.0002_add_data_domain... OK
  Unapplying ufdl-image-classification.0001_initial... OK
  Unapplying ufdl-core.0007_job_types... OK
  Unapplying ufdl-core.0006_framework... OK
  Unapplying ufdl-core.0005_cuda... OK
  Unapplying ufdl-core.0004_hardware... OK
  Unapplying ufdl-core.0003_standard_licences... OK
Traceback (most recent call last):
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1553, "Cannot drop index 'unique_job_types_per_docker_image': needed in a foreign key constraint")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/api_site/scripts/reset.py", line 40, in <module>
    reset()
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/api_site/scripts/reset.py", line 15, in reset
    main([script, "migrate", "ufdl-core", "zero"])
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/ufdl/api_site/scripts/manage.py", line 17, in main
    execute_from_command_line(argv)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/migrations/executor.py", line 121, in migrate
    state = self._migrate_all_backwards(plan, full_plan, fake=fake)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/migrations/executor.py", line 196, in _migrate_all_backwards
    self.unapply_migration(states[migration], migration, fake=fake)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/migrations/executor.py", line 269, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/migrations/migration.py", line 175, in unapply
    operation.database_backwards(self.app_label, schema_editor, from_state, to_state)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 832, in database_backwards
    schema_editor.remove_constraint(model, self.constraint)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 351, in remove_constraint
    self.execute(sql)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/fracpete/development/projects/waikato-ufdl/ufdl-backend/venv.dev/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1553, "Cannot drop index 'unique_job_types_per_docker_image': needed in a foreign key constraint")
```
Yesterday, I couldn't drop some of the tables manually. Instead, I had to drop the database and re-create it in order to get a clean slate. Maybe related?

**Comment by csterling** [comment]
Yeah it could be. It seems like it might be an ordering issue...

I've set up MySQL and am getting the same error, just working on it now. But I came across an error on first migration where one of the names of the pre-trained models was too long for the database. Did you get that as well?

**Comment by fracpete** [comment]
Haven't seen that error, but that was probably due to my database instance not running in strict mode and silently truncating the name. The name should be longer than 64 chars (make it 200).

**Comment by csterling** [comment]
Okay, so I've implemented another crack at this in 9158e25f189408191a892be36860e8aebe034f9d.

It basically just has a special case for using a MySQL database where it executes custom SQL to drop and recreate the database. It's a bit dirty but there you go.

**Comment by fracpete** [comment]
Yes, that worked. Wouldn't that *hack* work for all database types? Including sqlite and postgresql?

**Comment by csterling** [comment]
For SQLite, I'm not sure you can drop the database as such, as the database is the file, which is sort of what it does anyway (deletes the file from disk).

For other SQL databases, I imagine that something similar would work, down to using the correct SQL dialect and the `database()` (or equivalent) function being available.

Beyond that, I don't know.

**Comment by fracpete** [comment]
We'll leave for the time being at having support for sqlite (development purposes) and MySQL (production purposes).
