### ISSUE TITLE
Bottleneck in polygon annotations

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/ufdl-backend#73]
@fracpete has pointed out a possible bottleneck in uploading object-detection annotations, where annotations with polygons are taking an inordinate amount of time to upload.

- Determine the source of the bottleneck.
- Remove bottleneck.

**Comment by fracpete** [comment]
Just tried generating a smaller dataset so I can continue with object detection integration. It looks like the insertion times get slower and slower. Below are the timestamps from the logging output:

```
10:25:44
10:25:48
10:25:58
10:26:13
10:26:32
10:26:55
10:27:23
10:27:55
10:28:31
10:29:09
10:29:51
10:30:38
10:31:29
10:32:25
10:33:24
```
And as a simple plot:

![timestamps](https://user-images.githubusercontent.com/1026180/94619388-50caf780-0309-11eb-99cf-c2d0a3d0018d.png)

It almost looks like the database is slowing things down? Are there checks happening on un-indexed fields maybe?

**Comment by csterling** [comment]
@fracpete I have a theory that this is to do with serialisation/deserialisation of the annotations for each add call, so I have pushed a test branch `test_od_perf` which disables validation for these steps. Can you please re-run your test with this branch active and see if it helps things?

**Comment by fracpete** [comment]
The problem still persists:

```

04:29:51
--
04:29:55
04:30:02
04:30:13
04:30:26
04:30:44
04:31:04
04:31:26
04:31:54
04:32:23
04:32:54
04:33:29
04:34:09
04:34:50
04:35:32
```

![times](https://user-images.githubusercontent.com/1026180/94762883-5d347a80-0405-11eb-8950-845d3fb9b4bd.png)

The worrying thing is the increasing time (exponential?), each submission of annotations takes longer than the previous one. Hence I don't think so that it is the serialization. Probably more like checks against the database and/or inserts.

**Comment by csterling** [comment]
I've added some profiling code to the method for adding annotations to `od` data-sets, and the serialisation/deserialisation steps are definitely the bottleneck. It's just not the validation step of that process that is causing the slow-down, hence the previous patch had little effect.

I'll do some more research tomorrow into ways to speed this up.

**Comment by csterling** [comment]
@fracpete In 450e2477652096363863235c1cf9ac386d3c01fb I've modified the annotation processing to use a "raw" representation of JSON, which should speed things up. However there is still an increase in add-time as more annotations/images are added to the data-set, as the (albeit faster) raw serialisation is still having to work with a larger representation.

Please re-test when you get a chance.

**Comment by fracpete** [comment]
Performance is definitely better.

```
12:59:36
12:59:37
12:59:39
12:59:42
12:59:46
12:59:51
12:59:56
13:00:02
13:00:09
13:00:17
13:00:25
13:00:34
13:00:43
13:00:54
13:01:05
```

![times](https://user-images.githubusercontent.com/1026180/94875069-24051480-04b0-11eb-8e3e-20cee1454453.png)

Does the serialization have to work on dataset? After all, we are working on a per file basis (upload file, upload annotations for file).

**Comment by csterling** [comment]
This would require being able to modify the serialised representation of the annotations without deserialising them first (how it is currently done). I think this would be feasible it we laid out the serialised form differently. I'll have a crack at this.

**Comment by fracpete** [comment]
That would worthwhile looking into. I also noticed that submitting a yolact job (object detection using shape annotations) takes quite a long time compared to other job submissions. I presume that might be also due to the de-/serialization of the dataset at the backend?

**Comment by fracpete** [comment]
And listing of datasets gets slow as well, once you have an object detection dataset in there.

**Comment by csterling** [comment]
This issue is resolved in commit a18e496823b7f69f87a3ae58661100b7051b7442.

The solution was to allow the different domains of datasets to represent their annotations themselves. Object detection datasets now create a separate table for storing the annotations for each image separately, so that serialisation/deserialisation time isn't dependent on the number on the number of images in the dataset.
